### ISSUE TITLE
Unable to access cookbooks in the WebUI

### ISSUE THREAD

**Issue by harsh-garg98** [aiverify-foundation/moonshot#330] opened 2024-09-04 11:18 UTC
Hi,
I am trying to create new recipes and cookbooks but I can't navigate to the /benchmarking/cookbooks and the /benchmarking/recipes pages. I am getting the following error on the console:
```
2024-09-04 12:11:39,085] [INFO] [moonshot.integrations.web_api.app]: Request origin: None
[2024-09-04 12:11:39,092] [INFO] [uvicorn.access]: 127.0.0.1:60272 - "GET /api/v1/benchmarks/status HTTP/1.1" 200
TypeError: Cannot read properties of undefined (reading 'name')
    at b (/Users/harshgarg/Desktop/important/moonshot/moonshot-ui/.next/server/app/benchmarking/cookbooks/page.js:1:6628)
    at nj (/Users/harshgarg/Desktop/important/moonshot/moonshot-ui/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
    at nM (/Users/harshgarg/Desktop/important/moonshot/moonshot-ui/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
    at nN (/Users/harshgarg/Desktop/important/moonshot/moonshot-ui/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nB (/Users/harshgarg/Desktop/important/moonshot/moonshot-ui/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
    at nD (/Users/harshgarg/Desktop/important/moonshot/moonshot-ui/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66680)
    at nN (/Users/harshgarg/Desktop/important/moonshot/moonshot-ui/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64853)
    at nB (/Users/harshgarg/Desktop/important/moonshot/moonshot-ui/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
    at nM (/Users/harshgarg/Desktop/important/moonshot/moonshot-ui/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:58560)
    at nN (/Users/harshgarg/Desktop/important/moonshot/moonshot-ui/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546) {
  digest: '2447018243'
}
```
and the following error on the Chrome console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at k (3458-2c2f2c3ef279ac01.js:1:7477)
    at rE (fd9d1056-41335698810c3013.js:1:40342)
    at l$ (fd9d1056-41335698810c3013.js:1:59317)
    at iZ (fd9d1056-41335698810c3013.js:1:117680)
    at ia (fd9d1056-41335698810c3013.js:1:95163)
    at fd9d1056-41335698810c3013.js:1:91089
    at fd9d1056-41335698810c3013.js:1:91096
    at oZ (fd9d1056-41335698810c3013.js:1:91201)
    at MessagePort.T (7023-82c2e4037ef4f288.js:1:83731)
    
k | @ | 3458-2c2f2c3ef279ac01.js:1
-- | -- | --
  | rE | @ | fd9d1056-41335698810c3013.js:1
  | l$ | @ | fd9d1056-41335698810c3013.js:1
  | iZ | @ | fd9d1056-41335698810c3013.js:1
  | ia | @ | fd9d1056-41335698810c3013.js:1
  | (anonymous) | @ | fd9d1056-41335698810c3013.js:1
  | (anonymous) | @ | fd9d1056-41335698810c3013.js:1
  | oZ | @ | fd9d1056-41335698810c3013.js:1
  | T | @ | 7023-82c2e4037ef4f288.js:1
  | setTimeout (async) |   |  
  | oZ | @ | fd9d1056-41335698810c3013.js:1
  | T | @ | 7023-82c2e4037ef4f288.js:1

```

Please help me debug this issue!
Thanks!

**Comment by jacksonboey** [comment] 2024-09-05 02:07
Hi @harsh-garg98 , possible if can let us know the steps to reproduce the issue for investigation above thank you

**Comment by imda-amdlahir** [comment] 2024-10-03 07:29
Closing this issue because it has no more activity for more than 2 weeks. We are unable to reproduce this issue. If you face a similar issue, please raise a new one

**Closed by imda-amdlahir** 2024-10-03 07:29 UTC
